### ISSUE TITLE
NaN in timezoneOffset

### ISSUE THREAD

**Issue by Coding-Kiwi** [arncet/timestamp-utils#179]
OS: Windows 11
Browser: Brave Version 1.40.107 Chromium: 103.0.5060.53

I'm experiencing a weird bug.. I already tried some debugging, the function timezoneOffset in utils.js is called with "Europe/Berlin"
the variables `utc` and `current` are filled with `"June 26, 2022 at 07:55:08 PM"` and `"June 26, 2022 at 05:55:08 PM"`
and then `new Date(current)` returns `NaN`

![image](https://user-images.githubusercontent.com/5007641/175827647-95850c16-079a-4802-877f-cc45d3f7ff9f.png)

This results in everything failing because `this.timezoneOffset` is `NaN`

**Comment by Coding-Kiwi** [comment]
`new Date` has to be called with a string that can be parsed by `Date.parse`
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date

>When parsing date strings with the Date constructor (and Date.parse, they are equivalent), always make sure that the input conforms to the ISO 8601 format (YYYY-MM-DDTHH:mm:ss.sssZ) — the parsing behavior with other formats is implementation-defined and may not work across all browsers

**Comment by arncet** [comment]
Hello @Coding-Kiwi, thanks for this report, im looking right now for a fix.

**Comment by arncet** [comment]
Hello, @Coding-Kiwi the issue comes from the extra `at` in the string passed to `new Date(...)`.
I'm still investigate to find a fix.

**Comment by Coding-Kiwi** [comment]
> Hello, @Coding-Kiwi the issue comes from the extra `at` in the string passed to `new Date(...)`. I'm still investigate to find a fix.

As linked above passing anything that is not iso 8601 into the `new Date` is implementation-defined, each browser can handle it differently! So I guess best way would be to go with iso 8601

**Comment by arncet** [comment]
There is the fix : https://github.com/arncet/timestamp-utils/pull/183.

**Comment by arncet** [comment]
A new version is now available [v2.2.0](https://github.com/arncet/timestamp-utils/releases/tag/2.2.0).
Thanks @Coding-Kiwi for your help.
